// AUTO-GENERATED by scripts/generate-gone-routes.cjs — do not edit manually.
// Regenerated on each build via: node scripts/generate-gone-routes.cjs
//
// Contains Shopify product handles that are KNOWN to be dead (removed from Shopify
// or returning 404/410/500 on the storefront). These get a hard HTTP 410 Gone
// response in middleware.ts so Google drops them from the index faster than a
// 404 would.
//
// Source: dist/dead-product-handles.json (produced by scripts/generate-sitemap.cjs
// after HEAD-checking every Shopify product URL against the live site).
//
// Last generated: 2026-07-04T20:16:50.698Z
// Handle count: 0

export const GONE_PRODUCT_HANDLES: Set<string> = new Set<string>([]);
