// AUTO-GENERATED by scripts/prerender.js — do not edit manually.
// Contains the exact set of product handles with a prerendered HTML file in dist/_prerender/product/.
// Regenerated on each build. Imported by middleware.ts to avoid self-HTTP HEAD requests.
// This file is empty until the first successful build with SHOPIFY_STOREFRONT_TOKEN set.

export const PRERENDERED_PRODUCT_HANDLES: Set<string> = new Set([
]);
