project_id = "mxrvlizhrofsroydenti"

[functions.get-order]
verify_jwt = true

[functions.order-webhook]
verify_jwt = false

[functions.sync-products]
verify_jwt = false

[functions.virtual-tryon]
verify_jwt = true