import { rewrite, next } from '@vercel/functions';
import { fetchProductByHandle } from './src/middleware/shopifyProxy.js';
import { generateProductHtml, return404 } from './src/middleware/htmlGenerator.js';
import { PRERENDERED_ROUTES } from './src/lib/autoRoutes.js';
import { PRERENDERED_PRODUCT_HANDLES } from './src/lib/prerenderManifest.js';
import { GONE_PRODUCT_HANDLES } from './src/lib/goneRoutes.js';
import { getJewelryProductByHandle, generateJewelryProductHtml } from './src/middleware/jewelryFallback.js';

/**
 * Vercel Edge Middleware (non-Next.js / Vite)
 *
 * Serves the same prerendered or server-rendered HTML to every user agent.
 * This prevents crawler-only 404s and metadata differences while retaining
 * Shopify-backed rendering for products added after the latest deployment.
 */

// ─── Pre-rendered Routes ─────────────────────────────────────────────────────
// Auto-generated by scripts/generate-routes.cjs at build time.
// Includes all static pages and blog posts. Product routes are handled
// dynamically by the SSR path below, so they are NOT in this Set.
// See src/lib/autoRoutes.ts for the full list.

// Legacy regional pages that must 301 redirect to /nri
const LEGACY_REGIONAL_REDIRECT_ROUTES = new Set([
  '/nri/uk',
  '/indian-ethnic-wear-uk',
  '/uk-indian-clothing',
  '/uk-designer-sarees',
]);

// Confirmed one-to-one replacements for legacy product handles that still earn
// Google impressions. Run before the 410/404 checks so ranking signals transfer
// to the same current product instead of being discarded.
const PRODUCT_301_REDIRECTS: Record<string, string> = {
  '/product/green-net-sequins-occasion-lehenga-choli': '/product/green-net-sequins-lehenga-choli-with-dupatta',
  '/product/beads-work-lehenga-choli-in-satin-off-white': '/product/off-white-satin-beads-bridal-lehenga-with-dupatta',
  '/product/light-pink-net-beads-festive-lehenga-choli': '/product/light-pink-net-beads-bridal-lehenga-with-dupatta',
  '/product/rust-orange-georgette-embroidery-occasion-lehenga-choli': '/product/rust-orange-georgette-embroidery-lehenga-choli-with-dupatta',
  '/product/wine-pure-vichitra-embroidery-festive-lehenga-choli': '/product/wine-pure-vichitra-embroidery-lehenga-choli-with-dupatta',
  '/product/chinon-silk-pink-occasional-wear-embroidery-work-readymade-sharara-suit': '/product/luxemia-pink-chinon-silk-embroidery-work-occasional-wear-sharara-suit',
  '/product/faux-satin-silk-rani-pink-casual-wear-embroidery-work-readymade-sharara-suit-2': '/product/luxemia-baby-pink-faux-satin-silk-embroidery-work38-40-42-44-casual-wear-sharara-suit',
  '/product/viscose-jacquard-purple-festival-wear-jacquard-work-readymade-sharara-suit': '/product/luxemia-purple-viscose-jacquard-jacquard-work-festival-wear-sharara-suit',
  '/product/net-orange-festival-wear-embroidery-work-readymade-sharara-suit': '/product/luxemia-orange-net-embroidery-work-festival-wear-sharara-suit',
  '/product/net-turquoise-festival-wear-embroidery-work-readymade-sharara-suit': '/product/luxemia-turquoise-net-embroidery-work-festival-wear-sharara-suit',
  '/product/net-pink-festival-wear-embroidery-work-readymade-sharara-suit': '/product/luxemia-pink-net-embroidery-work-festival-wear-sharara-suit',
  '/product/chinon-silk-yellow-occasional-wear-embroidery-work-readymade-sharara-suit': '/product/luxemia-yellow-chinon-silk-embroidery-work-occasional-wear-sharara-suit',
  // Verified same garment: legacy naming was normalized, but the current yellow
  // Crunchy Silk Zari Anarkali listing remains the matching purchasable product.
  '/product/zari-work-anarkali-suit-in-crunchy-silk-yellow': '/product/yellow-crunchy-silk-zari-anarkali-suit-with-dupatta',
  // Verified retired-inventory replacements. Each source and destination share
  // the named garment, color, fabric, and work; do not add a generic fallback.
  '/product/blue-net-sequins-occasion-lehenga-choli': '/product/blue-net-sequins-lehenga-choli-with-dupatta',
  '/product/dark-blue-pure-vichitra-embroidery-festive-lehenga-choli': '/product/dark-blue-pure-vichitra-embroidery-lehenga-choli-with-dupatta',
  '/product/embroidery-work-lehenga-choli-in-dola-silk-beige': '/product/beige-dola-silk-embroidery-bridal-lehenga-with-dupatta',
  '/product/embroidery-work-lehenga-choli-in-faux-georgette-red': '/product/red-faux-georgette-embroidery-lehenga-choli-with-dupatta',
  '/product/embroidery-work-lehenga-choli-in-net-golden': '/product/golden-net-embroidery-lehenga-choli-with-dupatta-397817',
  '/product/embroidery-work-lehenga-choli-in-net-white': '/product/white-net-embroidery-lehenga-choli-with-dupatta',
  '/product/embroidery-work-lehenga-choli-in-pure-banarasi-green': '/product/green-pure-banarasi-embroidery-bridal-lehenga-with-dupatta',
  '/product/fendy-silk-teal-blue-festival-wear-embroidery-work-readymade-plazzo-suit': '/product/teal-blue-fendi-silk-embroidery-palazzo-suit-with-dupatta',
  '/product/georgette-pastle-teal-wedding-wear-zari-work-anarkali-suit': '/product/pastel-teal-georgette-zari-anarkali-suit-wsuit-018',
  '/product/golden-net-embroidery-festive-lehenga-choli': '/product/golden-net-embroidery-lehenga-choli-with-dupatta-397817',
  '/product/ivory-sequin-zari-bridal-lehenga-with-tissue-patchwork-stone-work': '/product/ivory-sequin-zari-bridal-lehenga-with-tissue-patchwork-and-stone-work',
  '/product/lavender-net-thread-occasion-lehenga-choli-designer-indian-lehenga': '/product/lavender-net-thread-lehenga-choli-with-dupatta',
  '/product/luxemia-light-pink-embroidered-shimmer-silk-palazzo-suit-for-wedding-guests': '/product/light-pink-shimmer-silk-embroidered-palazzo-suit-wsuit-008',
  '/product/luxemia-mint-green-faux-georgette-sequins-work-party-wear-sharara-suit': '/product/faux-georgette-mint-green-party-wear-sequins-work-readymade-sharara-suit',
  '/product/luxemia-pink-embroidered-chinon-palazzo-suit-for-wedding-guests': '/product/pink-chinon-embroidered-palazzo-suit-wsuit-002',
  '/product/luxemia-rani-pink-embroidered-chinon-palazzo-suit-for-wedding-guests': '/product/rani-pink-chinon-embroidered-palazzo-suit-wsuit-001',
  '/product/luxemia-sky-blue-embroidered-chinon-anarkali-suit-for-wedding-guests': '/product/sky-blue-chinon-embroidered-anarkali-suit-wsuit-005',
  '/product/luxemia-teal-green-embroidered-shimmer-silk-palazzo-suit-for-wedding-guests': '/product/teal-green-shimmer-silk-embroidered-palazzo-suit-wsuit-007',
  '/product/pink-net-thread-occasion-lehenga-choli': '/product/pink-net-thread-lehenga-choli-with-dupatta',
  '/product/pure-chinon-yellow-occasional-wear-embroidery-work-readymade-sharara-suit': '/product/luxemia-yellow-chinon-silk-embroidery-work-occasional-wear-sharara-suit',
  '/product/rani-pink-net-sequins-occasion-lehenga-choli': '/product/rani-pink-net-sequins-lehenga-choli-with-dupatta',
  '/product/sequins-work-designer-saree-in-satin-silk-light-pink': '/product/satin-silk-pink-occasional-wear-sequins-work-saree',
  '/product/teal-green-net-sequins-festive-lehenga-choli': '/product/teal-green-net-sequins-lehenga-choli-with-dupatta',
  '/product/wine-silk-embroidery-festive-lehenga-choli': '/product/wine-silk-embroidery-lehenga-choli-with-dupatta',
};

// Explicit 410 Gone routes — URLs that have been permanently retired and have
// NO semantic replacement. Only manually confirmed deletions belong here.
//
// Format: full pathname starting with '/'.
// Example: '/collections/some-old-collection', '/some-old-landing-page'
const GONE_ROUTES: Set<string> = new Set<string>([
  // ── Manually maintained entries (add retired URLs from GSC export here) ──
  // Product was deleted from Shopify but still gets GSC impressions (8 imp, 1 click
  // at pos 6.38 as of 2026-07-11). 410 tells Google to drop it from the index
  // immediately, vs. 404 which Google retries for weeks.
  '/product/art-silk-pista-green-groom-wear-thread-work-readymade-sherwani',
  // Search Console redirect examples checked on 22 Aug 2026. Shopify searches
  // found no exact active replacement, so these retired product URLs must not
  // redirect shoppers or crawlers to unrelated catalog items.
  '/product/luxemia-off-white-sequin-work-net-lehenga-choli-for-sangeet-and-wedding-guests',
  '/product/black-cotton-embroidered-men-s-kurta-pajama-set',
  // Current 404s from the 22 Aug 2026 Search Console crawled-not-indexed
  // examples. The three blog slugs have no published source route; the product
  // handles are absent from Shopify, except one explicitly archived product.
  // No exact live replacement was source-verified for any of them.
  '/blog/designer-wedding-dress-under-50000',
  '/blog/red-bridal-lehenga-trends-2026',
  '/blog/unstitched-vs-ready-to-wear-vs-made-to-measure',
  '/product/chinon-lime-yellow-wedding-wear-embroidery-work-readymade-sharara-suit',
  '/product/chinon-silk-orange-occasional-wear-embroidery-work-readymade-plazzo-suit',
  '/product/classic-bridal-red-silk-lehenga',
  '/product/faux-georgette-wine-occasional-wear-sequins-work-readymade-sharara-suit',
  '/product/georgette-green-occasional-wear-embroidery-work-readymade-plazzo-suit',
  '/product/georgette-rani-pink-festival-wear-embroidery-work-readymade-sharara-suit',
  '/product/lilac-linen-cotton-embroidered-men-s-kurta-pajama-set',
  '/product/luxemia-black-chinon-silk-embroidery-work-occasional-wear-sharara-suit',
  '/product/luxemia-brown-embroidered-art-silk-indo-western-for-south-asian-weddings',
  '/product/luxemia-front-cut-western-top-set',
  '/product/luxemia-olive-green-embroidered-satin-lehenga-choli-for-sangeet-and-wedding-guests',
  '/product/luxemia-tissue-brocade-pre-draped-saree',
  '/product/net-black-eid-wear-sequins-work-sharara-suit',
  '/product/pure-gmy-silk-red-eid-wear-embroidery-work-readymade-pakistani-suit',
  '/product/royal-rani-pink-silk-bridal-lehenga',
  '/product/shimmer-silk-sky-blue-occasional-wear-mirror-work-readymade-plazzo-suit',
  '/product/silk-green-occasional-wear-mirror-work-readymade-patiyala-suit',
  '/product/wine-net-embroidery-festive-lehenga-choli',
  // Google-selected-canonical examples checked on 22 Aug 2026. All seven
  // handles are absent from Shopify and have no source-verified replacement.
  '/product/art-silk-cream-groom-wear-thread-work-readymade-sherwani',
  '/product/chinon-navy-blue-occasional-wear-embroidery-work-readymade-plazzo-suit',
  '/product/georgette-purple-wedding-wear-embroidery-work-readywar-plazzo-suit',
  '/product/luxemia-multicolor-mirror-work-cotton-lehenga-choli-for-sangeet-and-wedding-guests',
  '/product/luxemia-navy-blue-hand-worked-imported-lachka-indo-western-for-south-asian-weddings',
  '/product/teal-blue-art-silk-patterned-sherwani-style-kurta-pajama-set',
  '/product/wine-art-banarasi-silk-patterned-men-s-kurta-pajama-with-jacket',
]);

// Combine manual GONE_ROUTES with auto-discovered dead product handles from build.
// This produces 410 Gone for any /product/{handle} in the set.
function isGoneProductPath(pathname: string): boolean {
  if (!pathname.startsWith('/product/')) return false;
  const handle = pathname.replace('/product/', '');
  return handle.length > 0 && !handle.includes('/') && GONE_PRODUCT_HANDLES.has(handle);
}

// Helper: emit a 410 Gone response with proper noindex headers.
function return410(): Response {
  const html = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">` +
    `<meta name="viewport" content="width=device-width,initial-scale=1">` +
    `<meta name="robots" content="noindex,nofollow">` +
    `<title>410 Gone — LuxeMia</title></head><body>` +
    `<h1>410 — This page has been permanently removed.</h1>` +
    `<p>The content you were looking for is no longer available.</p>` +
    `<p><a href="/">Return to LuxeMia homepage</a> ` +
    `or <a href="/collections">browse our collections</a>.</p></body></html>`;
  return new Response(html, {
    status: 410,
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'public, max-age=86400',
      'X-Robots-Tag': 'noindex, nofollow',
    },
  });
}

function withResponseHeader(response: Response, key: string, value: string): Response {
  const headers = new Headers(response.headers);
  headers.set(key, value);
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

// Query parameters that create filter, sort, grid, or internal-search URL noise.
// These URLs remain usable for shoppers, but should not become separate organic
// landing pages. Product ?variant= is intentionally excluded: it may be a valid
// product-variant or Merchant landing URL and receives canonical-only handling.
const INDEXATION_NOISE_PARAMS = new Set<string>([
  'sort_by',
  'filter',
  'grid',
  'q',
  'sub',
  'color',
  'fabric',
  'size',
  'price_min',
  'price_max',
  'section_id',
]);

function isIndexationNoiseParam(name: string): boolean {
  const normalized = name.toLowerCase();
  return (
    INDEXATION_NOISE_PARAMS.has(normalized)
    || normalized.startsWith('filter.')
    || normalized.startsWith('filter[')
    || normalized.startsWith('options[')
  );
}

function hasIndexationNoiseParams(searchParams: URLSearchParams): boolean {
  for (const name of searchParams.keys()) {
    if (isIndexationNoiseParam(name)) return true;
  }
  return false;
}

function isPublicHtmlPath(pathname: string): boolean {
  if (pathname.includes('.')) return false;

  const nonPublicPrefixes = [
    '/_prerender',
    '/assets',
    '/api',
    '/catalogs',
    '/admin',
    '/account',
    '/auth',
    '/wishlist',
    '/cart',
    '/checkout',
    '/order-confirmation',
  ];

  return !nonPublicPrefixes.some(
    (prefix) => pathname === prefix || pathname.startsWith(`${prefix}/`),
  );
}

function withCanonicalQuerySignals(request: Request, response: Response): Response {
  const url = new URL(request.url);
  if (!url.search || response.status !== 200 || !isPublicHtmlPath(url.pathname)) {
    return response;
  }

  const existingRobots = response.headers.get('X-Robots-Tag')?.toLowerCase() || '';
  if (existingRobots.includes('nofollow')) return response;

  const headers = new Headers(response.headers);
  headers.set('Link', `<https://luxemia.shop${url.pathname}>; rel="canonical"`);

  if (hasIndexationNoiseParams(url.searchParams)) {
    headers.set('X-Robots-Tag', 'noindex, follow');
  }

  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

// ─── Main Middleware ─────────────────────────────────────────────────────────

export default async function middleware(request: Request) {
  let response = await routeRequest(request);
  response = withCanonicalQuerySignals(request, response);
  const hostname = new URL(request.url).hostname.toLowerCase();

  // Vercel/Lovable preview URLs remain usable for QA, but can never compete
  // with luxemia.shop in search. The HTTP directive also covers pages whose
  // client-side metadata has not hydrated yet.
  if (hostname !== 'luxemia.shop' && hostname !== 'www.luxemia.shop') {
    return withResponseHeader(response, 'X-Robots-Tag', 'noindex, nofollow');
  }

  return response;
}

async function routeRequest(request: Request): Promise<Response> {
  const url = new URL(request.url);
  const { pathname } = url;

  // ── Canonical origin: redirect HTTP/www → HTTPS apex (301 permanent) ──────
  // All canonical URLs in prerendered HTML and sitemap use https://luxemia.shop
  // (non-www). Consolidating ensures GSC treats them as one property and avoids
  // duplicate-content signals across the two versions. Using 301 (not 308) for
  // maximum crawler compatibility (some older crawlers and third-party SEO tools
  // handle 308 inconsistently).
  if (
    (url.hostname === 'www.luxemia.shop' || url.hostname === 'luxemia.shop')
    && (url.hostname !== 'luxemia.shop' || url.protocol !== 'https:')
  ) {
    const canonical = new URL(request.url);
    canonical.hostname = 'luxemia.shop';
    canonical.protocol = 'https:';
    canonical.port = '';
    return Response.redirect(canonical.toString(), 301);
  }

  if (pathname.length > 1 && pathname.endsWith('/')) {
    const canonical = new URL(request.url);
    canonical.pathname = pathname.replace(/\/+$/, '');
    return Response.redirect(canonical.toString(), 301);
  }

  // Featured duplicated New Arrivals product-for-product. Consolidate the old
  // URL so shoppers and search engines have one current discovery page.
  if (pathname === '/bestsellers') {
    return Response.redirect(new URL('/new-arrivals', request.url).toString(), 301);
  }

  // Static assets and machine-readable files (including merchant-feed.xml) are
  // served directly by Vercel. The feed is generated and validated at build time.
  if (
    pathname.startsWith('/_prerender') ||
    pathname.startsWith('/assets') ||
    pathname.startsWith('/api') ||
    pathname.startsWith('/catalogs') ||
    pathname.includes('.')
  ) {
    return next();
  }

  // Strip query parameters from collection/category filter URLs for every
  // client. Serving the same response to crawlers and shoppers avoids
  // user-agent-dependent rendering while keeping filtered URLs out of search.
  // URLs like /lehengas?sub=wedding-guest or /sarees?color=red should NOT be
  // indexed as separate pages — they cause duplicate content and waste crawl
  // budget. Serve the canonical category page with a noindex header so Google
  // drops the parameterized URL from the index.
  if (url.search) {
    const cleanPath = pathname; // without query params
    // Only strip params from known category/collection routes
    const CATEGORY_ROUTES = new Set([
      '/lehengas', '/sarees', '/suits', '/menswear', '/jewelry',
      '/indowestern', '/new-arrivals', '/collections',
    ]);
    if (CATEGORY_ROUTES.has(cleanPath) || cleanPath.startsWith('/collections/')) {
      // Return the clean URL's content but with noindex to drop the param URL
      if (PRERENDERED_ROUTES.has(cleanPath)) {
        const prerenderPath = cleanPath === '/'
          ? '/_prerender/index.html'
          : `/_prerender${cleanPath}.html`;
        const resp = await fetch(new URL(prerenderPath, request.url));
        if (resp.ok) {
          const html = await resp.text();
          return new Response(html, {
            status: 200,
            headers: {
              'Content-Type': 'text/html; charset=utf-8',
              'X-Robots-Tag': 'noindex, follow',
              'Link': `<https://luxemia.shop${cleanPath}>; rel="canonical"`,
            },
          });
        }
      }
      return return404(request);
    }
  }

  // Preserve search equity when a legacy product has a confirmed replacement.
  if (PRODUCT_301_REDIRECTS[pathname]) {
    return Response.redirect(new URL(PRODUCT_301_REDIRECTS[pathname], request.url).toString(), 301);
  }

  // 410 Gone check — explicit, confirmed retired URLs only.
  // Confirmed replacement redirects above take precedence; every remaining
  // retired URL stays 410 instead of falling through to a generic redirect.
  if (GONE_ROUTES.has(pathname) || isGoneProductPath(pathname)) {
    return return410();
  }

  // 301 Permanent Redirect for legacy regional pages
  if (LEGACY_REGIONAL_REDIRECT_ROUTES.has(pathname)) {
    return Response.redirect(new URL('/nri', request.url).toString(), 301);
  }

  // 301 Permanent Redirect for canonical URL aliases
  if (pathname === '/privacy-policy') {
    return Response.redirect(new URL('/privacy', request.url).toString(), 301);
  }
  if (pathname === '/terms-of-service') {
    return Response.redirect(new URL('/terms', request.url).toString(), 301);
  }
  // /products has no React route — redirect to /collections to prevent soft 404
  if (pathname === '/products') {
    return Response.redirect(new URL('/collections', request.url).toString(), 301);
  }
  // The virtual try-on feature has been retired with no semantically equivalent
  // destination. A 410 accurately retires the old URL and avoids an irrelevant
  // homepage redirect that Google can classify as a soft 404.
  if (pathname === '/virtual-try-on') {
    return return410();
  }
  // 301 Permanent Redirect for /collections/* → canonical category pages.
  // These routes exist as client-side React Router <Navigate> redirects, but
  // bots need server-side 301s to properly transfer link equity and avoid
  // indexing the redirect-source URL with thin/empty SPA content.
  const COLLECTION_301_REDIRECTS: Record<string, string> = {
    '/collections/reception-outfits': '/collections',
    '/collections/festive-wear': '/collections',
    '/collections/sarees': '/sarees',
    '/collections/salwar-kameez': '/suits',
    '/collections/suits': '/suits',
    '/collections/menswear': '/menswear',
    '/collections/lehengas': '/lehengas',
    '/collections/pakistani-suits': '/suits',
    '/collections/pakistani-wedding-dresses': '/suits',
    '/collections/wedding-lehengas': '/lehengas',
    '/collections/indo-western': '/indowestern',
    '/collections/bridesmaid-dresses': '/sarees',
    '/collections/groomsman-outfits': '/menswear',
    '/collections/lehenga-choli': '/lehengas',
  };
  if (COLLECTION_301_REDIRECTS[pathname]) {
    return Response.redirect(new URL(COLLECTION_301_REDIRECTS[pathname], request.url).toString(), 301);
  }

  // Product pages use one response path for crawlers and shoppers. Existing
  // prerenders are fastest; products added since the latest deployment fall
  // back to live Shopify rendering. Missing handles always return a true 404.
  if (pathname.startsWith('/product/')) {
    const handle = pathname.replace('/product/', '');
    if (!handle || handle.includes('/')) {
      return return404(request);
    }
    if (PRERENDERED_PRODUCT_HANDLES.has(handle)) {
      return rewrite(new URL(`/_prerender/product/${handle}.html`, request.url));
    }

    const product = await fetchProductByHandle(handle);
    if (product) {
      const canonicalUrl = `https://luxemia.shop/product/${handle}`;
      return new Response(generateProductHtml(product, canonicalUrl), {
        status: 200,
        headers: {
          'Content-Type': 'text/html; charset=utf-8',
          'Cache-Control': 'public, max-age=600, s-maxage=3600, stale-while-revalidate=86400',
          'X-Robots-Tag': 'index, follow',
        },
      });
    }

    const jewelryProduct = getJewelryProductByHandle(handle);
    if (jewelryProduct) {
      const canonicalUrl = `https://luxemia.shop/product/${handle}`;
      return new Response(generateJewelryProductHtml(jewelryProduct, canonicalUrl), {
        status: 200,
        headers: {
          'Content-Type': 'text/html; charset=utf-8',
          'Cache-Control': 'public, max-age=600, s-maxage=3600, stale-while-revalidate=86400',
          'X-Robots-Tag': 'index, follow',
        },
      });
    }

    return return404(request);
  }

  // Preserve SEO equity for legacy size-guide URLs before the bot unknown-route
  // fallback, so crawlers receive the same 301 as normal visitors.
  const LEGACY_BLOG_REDIRECTS: Record<string, string> = {
    '/blog/indian-size-to-us-clothing-size-conversion-guide': '/blog/indian-to-us-clothing-size-conversion-guide',
    '/blog/indian-size-to-us-size-conversion-chart': '/blog/indian-to-us-clothing-size-conversion-guide',
    // The historic guides no longer have equivalent editorial pages. Send each
    // visitor to the closest live shopping destination rather than a dead URL.
    '/blog/banarasi-silk-saree-guide-authentic': '/collections/silk-sarees',
    '/blog/indian-bridal-jewelry-sets-complete-guide': '/jewelry',
  };
  if (LEGACY_BLOG_REDIRECTS[pathname]) {
    return Response.redirect(new URL(LEGACY_BLOG_REDIRECTS[pathname], request.url).toString(), 301);
  }

  // Every public indexable route is served from the same prerendered file to
  // every user agent. This removes the Googlebot-only branch that caused 52
  // valid URLs to return 404 after the July 23 migration deployment.
  if (PRERENDERED_ROUTES.has(pathname)) {
    const prerenderPath =
      pathname === '/'
        ? '/_prerender/index.html'
        : `/_prerender${pathname}.html`;
    return rewrite(new URL(prerenderPath, request.url));
  }

  // Account and administrative pages stay functional but are excluded from
  // search at the HTTP layer, before any client-side React metadata runs.
  const PRIVATE_SPA_ROUTES = new Set([
    '/wishlist',
    '/auth',
    '/account',
    '/admin',
    '/order-confirmation',
  ]);
  if (PRIVATE_SPA_ROUTES.has(pathname) || pathname.startsWith('/admin/')) {
    return withResponseHeader(next(), 'X-Robots-Tag', 'noindex, nofollow');
  }

  // No public route matched: return the same real 404 to shoppers, Googlebot,
  // social scrapers, and SEO tools. This eliminates remaining soft cloaking.
  return return404(request);
}

export const config = {
  matcher: [
    '/robots.txt',
    '/sitemap.xml',
    '/((?!_prerender|assets|api|favicon\\.ico|og-image\\.jpg|robots\\.txt|sitemap\\.xml|images|catalogs|3c4a52b9-542f-4bfe-a61b-9afb42f4312c\\.txt|google4e3f332d00afc8ba\\.html|.*\\.(?:js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2|csv|txt|xml|tsv)).*)',
  ],
};
