import { rewrite, next } from '@vercel/functions';
import { isBot } from './src/middleware/botDetection.js';
import { fetchProductByHandle } from './src/middleware/shopifyProxy.js';
import { generateProductHtml, return404, escapeHtml } from './src/middleware/htmlGenerator.js';
import { getCachedSpaHtml, setCachedSpaHtml } from './src/middleware/cache.js';
import { PRERENDERED_ROUTES } from './src/lib/autoRoutes.js';
import { PRERENDERED_PRODUCT_HANDLES } from './src/lib/prerenderManifest.js';

/**
 * Vercel Edge Middleware (non-Next.js / Vite)
 *
 * Detects search engine bot user agents and serves server-rendered HTML
 * with proper SEO content. Regular users get the normal SPA experience.
 *
 * CRITICAL FIX: For product pages accessed by bots/crawlers (including GMC's
 * page checker), we dynamically fetch product data from Shopify Storefront API
 * and generate complete HTML with meta tags, structured data, and visible content.
 * This fixes the "Product page unavailable" GMC error caused by SPA rendering.
 */

// ─── Pre-rendered Routes ─────────────────────────────────────────────────────
// Auto-generated by scripts/generate-routes.cjs at build time.
// Includes all static pages and blog posts. Product routes are handled
// dynamically by the SSR path below, so they are NOT in this Set.
// See src/lib/autoRoutes.ts for the full list.

// Routes that redirect elsewhere (should not be treated as 404)
const REDIRECT_ROUTES = new Set([
  '/our-story',
  '/lookbook',
  '/jewelry',
  '/collections/wedding-sarees',
  '/collections/bridal-lehengas',
  '/collections/reception-outfits',
  '/collections/festive-wear',
  '/collections/sarees',
  '/collections/salwar-kameez',
  '/collections/suits',
  '/collections/menswear',
  '/collections/lehengas',
  '/collections/indo-western',
  '/collections/bridesmaid-dresses',
  '/collections/groomsman-outfits',
]);

// Routes that must 308 redirect to /nri (UK pages no longer targeted)
const UK_REDIRECT_ROUTES = new Set([
  '/nri/uk',
  '/indian-ethnic-wear-uk',
  '/uk-indian-clothing',
  '/uk-designer-sarees',
]);

// ─── Main Middleware ─────────────────────────────────────────────────────────

export default async function middleware(request: Request) {
  const userAgent = request.headers.get('user-agent') || '';
  const url = new URL(request.url);
  const { pathname } = url;

  // Skip non-page requests (static files, API, etc.)
  if (
    pathname.startsWith('/_prerender') ||
    pathname.startsWith('/assets') ||
    pathname.startsWith('/api') ||
    pathname.startsWith('/catalogs') ||
    pathname.includes('.')
  ) {
    return next();
  }

  // 308 Permanent Redirect for UK pages (no longer targeted markets)
  if (UK_REDIRECT_ROUTES.has(pathname)) {
    return Response.redirect(new URL('/nri', request.url).toString(), 308);
  }

  // Product pages: serve prerendered HTML to ALL visitors (bots and humans) when
  // a prerendered file exists for this handle. PRERENDERED_PRODUCT_HANDLES is a
  // Set compiled into the middleware bundle at build time by generate-routes.cjs,
  // so we avoid any self-HTTP HEAD requests — zero extra latency, zero failure modes.
  //
  // Handles NOT in the set (products added to Shopify after the last deploy) fall
  // through to the bot-SSR path (live Shopify fetch) or the SPA shell for humans.
  if (pathname.startsWith('/product/')) {
    const handle = pathname.replace('/product/', '');
    if (handle && !handle.includes('/') && PRERENDERED_PRODUCT_HANDLES.has(handle)) {
      return rewrite(new URL(`/_prerender/product/${handle}.html`, request.url));
    }
  }

  // For bots: serve prerendered or dynamically-rendered content
  if (isBot(userAgent)) {
    // 1. Prerendered static routes → serve prerendered HTML
    if (PRERENDERED_ROUTES.has(pathname)) {
      const prerenderPath =
        pathname === '/'
          ? '/_prerender/index.html'
          : `/_prerender${pathname}.html`;

      return rewrite(new URL(prerenderPath, request.url));
    }

    // 2. Product pages → DYNAMIC SSR from Shopify API
    //    This is the CRITICAL FIX for GMC "Product page unavailable" errors.
    //    Instead of letting bots through to the SPA (which renders empty HTML
    //    that GMC can't crawl), we fetch product data from Shopify and generate
    //    complete HTML with meta tags, structured data, and visible content.
    if (pathname.startsWith('/product/')) {
      const handle = pathname.replace('/product/', '');

      // Try fetching from Shopify Storefront API
      const product = await fetchProductByHandle(handle);

      if (product) {
        const canonicalUrl = `https://luxemia.shop/product/${handle}`;
        const html = generateProductHtml(product, canonicalUrl);

        return new Response(html, {
          status: 200,
          headers: {
            'Content-Type': 'text/html; charset=utf-8',
            'Cache-Control': 'public, max-age=600, s-maxage=3600, stale-while-revalidate=86400',
            'X-Robots-Tag': 'index, follow',
          },
        });
      }

      // Product not found in Shopify → return 404 with noindex
      return return404(request);
    }

    // 3. Collection/category pages that aren't prerendered — let through to SPA
    if (pathname.startsWith('/collections/')) {
      return next();
    }

    // 4. /admin → noindex
    if (pathname.startsWith('/admin')) {
      return new Response(
        `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Admin | LuxeMia</title></head><body><p>Admin panel — not indexed.</p></body></html>`,
        {
          status: 200,
          headers: { 'Content-Type': 'text/html; charset=utf-8' },
        }
      );
    }

    // 5. Unknown route → proper HTTP 404
    if (!REDIRECT_ROUTES.has(pathname)) {
      return return404(request);
    }
  }

  // Regular users or redirect routes → inject proper meta tags into SPA HTML
  // CRITICAL SEO FIX: Previously, ALL non-bot visitors got the SPA shell with
  // identical homepage meta tags. Now we inject correct title, description,
  // canonical, and OG tags for every page so that social media scrapers,
  // browser tabs, and link previews work correctly for ALL visitors.
  return injectMetaIntoSpa(request, pathname);
}

// ─── SPA Meta Injection ────────────────────────────────────────────────────

/**
 * Fetch the SPA index.html and inject page-specific meta tags.
 * This ensures ALL visitors (not just bots) see correct title, description,
 * canonical URL, and Open Graph tags in the initial HTML response.
 *
 * This fixes the critical SEO issue where every page appeared identical
 * to social media scrapers and browser previews because the SPA shell
 * had only the homepage's meta tags.
 */
async function injectMetaIntoSpa(request: Request, pathname: string): Promise<Response> {
  // Get the SPA HTML (cached)
  let spaHtml = getCachedSpaHtml();
  if (!spaHtml) {
    try {
      const resp = await fetch(new URL('/index.html', request.url).toString());
      spaHtml = await resp.text();
      setCachedSpaHtml(spaHtml);
    } catch {
      // Fallback: let the normal SPA through
      return next();
    }
  }

  let html = spaHtml;

  // Determine the correct meta tags for this page
  let title = 'LuxeMia | Indian Ethnic Wear — Sarees & Lehengas';
  let description = 'Shop Indian ethnic wear at LuxeMia. Bridal lehengas, silk sarees, salwar suits & more. Free shipping on orders over $350 to USA, Canada & Australia.';
  let canonical = `https://luxemia.shop${pathname}`;
  let ogType = 'website';
  let ogImage = 'https://luxemia.shop/og-image.jpg';

  // For product pages: DO NOT call Shopify API for regular users.
  // The React app handles meta tags client-side via react-helmet-async.
  // Calling Shopify here adds 200-800ms TTFB for every product page hit.
  // Bots get full SSR HTML via the bot path above; regular users get
  // correct meta tags once React hydrates. Social media scrapers that
  // don't execute JS are caught by the isBot() check above.
  if (pathname.startsWith('/product/')) {
    const handle = pathname.replace('/product/', '');
    // Use a generic product meta tag — React will replace with real data on hydration
    const productName = handle.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
    title = `${productName} | Indian Ethnic Wear | LuxeMia`;
    description = `Shop ${productName} at LuxeMia. Premium quality Indian ethnic wear with free shipping on orders over $350 to USA, Canada & Australia.`.slice(0, 160);
    ogType = 'product';
    // Keep default ogImage — the React app will update it on hydration
  } else if (pathname.startsWith('/blog/')) {
    // Blog posts
    const slug = pathname.replace('/blog/', '');
    const blogMeta = getBlogMetadataMiddleware(slug);
    if (blogMeta) {
      title = blogMeta.title;
      description = blogMeta.description;
      ogType = 'article';
    }
  } else {
    // Static pages — use the metadata map
    const staticMeta = STATIC_PAGE_META[pathname];
    if (staticMeta) {
      title = staticMeta.title;
      description = staticMeta.description;
      if (staticMeta.image) ogImage = staticMeta.image;
    }
  }

  // Inject meta tags into the HTML
  const escapedTitle = escapeHtml(title);
  const escapedDesc = escapeHtml(description);
  const escapedCanonical = escapeHtml(canonical);
  const escapedOgImage = escapeHtml(ogImage);

  // Replace the title tag
  html = html.replace(
    /<title>[^<]*<\/title>/,
    `<title>${escapedTitle}</title>`
  );

  // Replace or add meta description
  if (html.includes('name="description"')) {
    html = html.replace(
      /<meta\s+name="description"\s+content="[^"]*"/,
      `<meta name="description" content="${escapedDesc}"`
    );
  } else {
    html = html.replace(
      '</head>',
      `<meta name="description" content="${escapedDesc}">\n</head>`
    );
  }

  // Replace or add canonical URL
  if (html.includes('rel="canonical"')) {
    html = html.replace(
      /<link\s+rel="canonical"\s+href="[^"]*"/,
      `<link rel="canonical" href="${escapedCanonical}"`
    );
  } else {
    html = html.replace(
      '</head>',
      `<link rel="canonical" href="${escapedCanonical}">\n</head>`
    );
  }

  // Replace or add OG tags
  const ogReplacements: [RegExp, string][] = [
    [/property="og:title"\s+content="[^"]*"/, `property="og:title" content="${escapedTitle}"`],
    [/property="og:description"\s+content="[^"]*"/, `property="og:description" content="${escapedDesc}"`],
    [/property="og:url"\s+content="[^"]*"/, `property="og:url" content="${escapedCanonical}"`],
    [/property="og:type"\s+content="[^"]*"/, `property="og:type" content="${ogType}"`],
    [/property="og:image"\s+content="[^"]*"/, `property="og:image" content="${escapedOgImage}"`],
    [/name="twitter:title"\s+content="[^"]*"/, `name="twitter:title" content="${escapedTitle}"`],
    [/name="twitter:description"\s+content="[^"]*"/, `name="twitter:description" content="${escapedDesc}"`],
    [/name="twitter:url"\s+content="[^"]*"/, `name="twitter:url" content="${escapedCanonical}"`],
    [/name="twitter:image"\s+content="[^"]*"/, `name="twitter:image" content="${escapedOgImage}"`],
  ];

  for (const [regex, replacement] of ogReplacements) {
    if (html.match(regex)) {
      html = html.replace(regex, replacement);
    }
  }

  return new Response(html, {
    status: 200,
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'public, max-age=300, s-maxage=3600, stale-while-revalidate=86400',
    },
  });
}

// ─── Static Page Metadata (for SPA meta injection) ──────────────────────────

interface PageMeta {
  title: string;
  description: string;
  image?: string;
}

const STATIC_PAGE_META: Record<string, PageMeta> = {
  '/': {
    title: 'LuxeMia | Indian Ethnic Wear — Sarees & Lehengas',
    description: 'Shop Indian ethnic wear at LuxeMia. Bridal lehengas, silk sarees, salwar suits & more. Free shipping on orders over $350 to USA, Canada & Australia. Affordable prices.',
    image: 'https://luxemia.shop/og-image.jpg',
  },
  '/sarees': {
    title: 'Buy Sarees Online | Indian Silk, Wedding & Banarasi Sarees - LuxeMia',
    description: 'Buy Indian sarees online at LuxeMia. Shop silk sarees, Banarasi, Kanchipuram wedding sarees, party wear & festive sarees. Free shipping to USA & Canada. Affordable prices.',
    image: 'https://luxemia.shop/og/og-sarees.jpg',
  },
  '/lehengas': {
    title: 'Buy Bridal Lehengas Online | Wedding & Festive Lehenga Choli - LuxeMia',
    description: 'Buy bridal lehengas online at LuxeMia. Shop wedding lehenga choli, festive lehengas & party wear in silk, net & velvet. Custom sizing available. Free shipping to USA & Canada.',
    image: 'https://luxemia.shop/og/og-lehengas.jpg',
  },
  '/suits': {
    title: 'Buy Salwar Kameez Online | Anarkali, Palazzo & Sharara Suits - LuxeMia',
    description: 'Buy salwar kameez online at LuxeMia. Shop Anarkali suits, Palazzo sets, Sharara suits & Pakistani suits. Free worldwide shipping. Affordable prices for USA & Canada.',
    image: 'https://luxemia.shop/og/og-suits.jpg',
  },
  '/menswear': {
    title: 'Buy Sherwani Online | Indian Ethnic Wear for Men - Groom & Wedding - LuxeMia',
    description: 'Buy Indian ethnic wear for men online at LuxeMia. Shop groom sherwanis, kurta pajama sets, velvet sherwanis & Nehru jackets. Custom sizing available. Free shipping worldwide.',
    image: 'https://luxemia.shop/og/og-menswear.jpg',
  },
  '/collections': {
    title: 'Buy Indian Ethnic Wear Online | All Collections - LuxeMia',
    description: 'Buy Indian ethnic wear online at LuxeMia. Shop our complete collection of bridal lehengas, sarees, salwar kameez, jewelry, menswear & indo-western outfits. Free worldwide shipping.',
  },
  '/blog': {
    title: 'Indian Ethnic Wear Blog — Bridal Lehengas, Saree Styles & Wedding Fashion | LuxeMia',
    description: 'Expert guides on Indian wedding dresses, bridal lehengas, saree styles & ethnic fashion for NRIs shopping from USA, Canada & Australia. Get insider tips from top stylists.',
  },
  '/brand-story': {
    title: 'Our Story — LuxeMia | Authentic Indian Ethnic Wear for USA, Canada & Australia',
    description: 'Discover the LuxeMia story. We source authentic Indian ethnic wear directly from India\'s textile hubs — Surat, Varanasi, Jaipur — and deliver quality-inspected sarees, lehengas & suits to the USA, Canada & Australia. Free shipping over $350.',
  },
  '/new-arrivals': {
    title: 'New Arrivals: Latest Indian Ethnic Wear Online | LuxeMia',
    description: 'Shop the latest Indian ethnic wear online at LuxeMia. New arrivals in bridal lehengas, designer sarees, salwar kameez, jewelry & more. Fresh styles added weekly. Free shipping.',
  },
  '/bestsellers': {
    title: 'Bestsellers: Most-Loved Indian Ethnic Wear Online | LuxeMia',
    description: 'Shop LuxeMia\'s bestselling Indian ethnic wear online. Most-loved bridal lehengas, sarees, salwar kameez & jewelry — trusted by customers worldwide. Free shipping.',
  },
  '/indowestern': {
    title: 'Buy Indo-Western Dresses Online | Fusion Indian Outfits - LuxeMia',
    description: 'Buy indo-western dresses online at LuxeMia. Shop fusion Indian outfits combining traditional embroidery with contemporary silhouettes. Perfect for modern occasions. Free shipping worldwide.',
  },
  '/nri': {
    title: 'Buy Indian Ethnic Wear Online | NRI Shopping | LuxeMia',
    description: 'Shop authentic Indian ethnic wear delivered to USA, Canada & Australia. Designer sarees, bridal lehengas, salwar suits & menswear. Free shipping on orders over $350. 7-10 day delivery.',
  },
  '/nri/usa': {
    title: 'Buy Indian Ethnic Wear Online USA | LuxeMia',
    description: 'Shop authentic Indian ethnic wear delivered to USA. Designer sarees, bridal lehengas, salwar suits & menswear. Flat rate shipping $25/order, free on orders over $350. 7-10 day standard delivery.',
  },
  '/nri/canada': {
    title: 'Buy Indian Ethnic Wear Online Canada | Sarees, Lehengas & Suits - LuxeMia',
    description: 'Buy Indian ethnic wear online in Canada. Shop sarees, bridal lehengas, salwar suits & menswear. Flat rate shipping $25/order, free on orders over $350. 7-10 day standard delivery to Canada.',
  },
  '/indian-ethnic-wear-usa': {
    title: 'Buy Indian Ethnic Wear Online USA | LuxeMia',
    description: 'Shop authentic Indian ethnic wear delivered to USA. Designer sarees, bridal lehengas, salwar suits & menswear. Flat rate shipping $25/order, free on orders over $350. 7-10 day standard delivery.',
  },
  '/indian-ethnic-wear-canada': {
    title: 'Buy Indian Ethnic Wear Online Canada | Sarees, Lehengas & Suits - LuxeMia',
    description: 'Buy Indian ethnic wear online in Canada. Shop sarees, bridal lehengas, salwar suits & menswear. Flat rate shipping $25/order, free on orders over $350. 7-10 day standard delivery to Canada.',
  },
  '/shipping': {
    title: 'Shipping Information — LuxeMia',
    description: 'LuxeMia ships to USA, Canada, and Australia at a flat rate of $25 per order. Free shipping on orders over $350. USPS/UPS/DHL delivery.',
  },
  '/returns': {
    title: 'Returns, Refunds & Cancellation Policy — LuxeMia',
    description: 'LuxeMia return, refund, and cancellation policy. All sales final. Damage claims require mandatory unboxing video. Cancellations accepted within 24 hours only.',
  },
  '/privacy': {
    title: 'Privacy Policy — LuxeMia',
    description: 'LuxeMia Privacy Policy. Learn how we collect, use, share, and protect your personal information when you shop Indian ethnic wear at luxemia.shop.',
  },
  '/terms': {
    title: 'Terms of Service — LuxeMia',
    description: 'Review the LuxeMia terms of service. Understand our policies on orders, payments, shipping, and returns before shopping.',
  },
  '/contact': {
    title: 'Contact Us — LuxeMia',
    description: 'Get in touch with LuxeMia. Questions about orders, sizing, or custom tailoring? Reach us via email, phone, or WhatsApp.',
  },
  '/faq': {
    title: 'Frequently Asked Questions — LuxeMia',
    description: 'Find answers to common questions about LuxeMia orders, shipping, sizing, returns, and product care.',
  },
  '/size-guide': {
    title: 'Size Guide — LuxeMia',
    description: 'Find your perfect fit with the LuxeMia size guide. Measurements for lehengas, sarees, salwar suits, and blouses with US and UK conversions.',
  },
  '/care-guide': {
    title: 'Garment Care Guide — LuxeMia',
    description: 'Care instructions for Indian ethnic wear. Learn how to preserve silk sarees, lehengas, and embroidered garments so they stay beautiful for years.',
  },
  '/style-consultation': {
    title: 'Personal Styling Consultation | Book a Session | LuxeMia',
    description: 'Book a free 30-minute virtual styling consultation with LuxeMia\'s expert stylists. Get personalized recommendations for Indian ethnic wear — sarees, lehengas, suits & more.',
  },
  '/style-quiz': {
    title: 'Find Your Style — LuxeMia Style Quiz',
    description: 'Take LuxeMia\'s style quiz to discover your perfect Indian ethnic wear look. Get personalised outfit recommendations in 5 quick questions.',
  },
};

// Blog metadata for middleware injection
function getBlogMetadataMiddleware(slug: string): { title: string; description: string } | null {
  const blogMap: Record<string, { title: string; description: string }> = {
    'sharara-suit-guide-2026-styles-fabrics': { title: 'Sharara Suit Guide 2026: Styles & Fabrics | LuxeMia Blog', description: 'Complete guide to sharara suits in 2026. Styles, fabrics, and styling tips at LuxeMia.' },
    'pakistani-suits-anarkali-shopping-guide': { title: 'Pakistani Suits & Anarkali Shopping Guide | LuxeMia Blog', description: 'Shopping guide for Pakistani suits and Anarkali sets at LuxeMia.' },
    'style-lehenga-choli-every-wedding-event': { title: 'Style Lehenga Choli for Every Wedding Event | LuxeMia Blog', description: 'Style your lehenga choli for every wedding event at LuxeMia.' },
    'indian-wedding-season-2026-outfit-guide': { title: 'Indian Wedding Season 2026 Outfit Guide | LuxeMia Blog', description: 'Complete outfit guide for Indian wedding season 2026 at LuxeMia.' },
    'fabric-guide-indian-ethnic-wear-georgette-silk-chiffon': { title: 'Fabric Guide: Georgette, Silk & Chiffon | LuxeMia Blog', description: 'Understanding Indian ethnic wear fabrics at LuxeMia.' },
    'indian-wedding-dress-complete-guide': { title: 'Indian Wedding Dress Complete Guide | LuxeMia Blog', description: 'Complete guide to Indian wedding dresses at LuxeMia.' },
    'red-bridal-lehenga-trends-2026': { title: 'Red Bridal Lehenga Trends 2026 | LuxeMia Blog', description: 'Latest red bridal lehenga trends for 2026 at LuxeMia.' },
    'designer-wedding-dress-under-50000': { title: 'Designer Wedding Dress Under ₹50,000 | LuxeMia Blog', description: 'Designer wedding dresses under ₹50,000 at LuxeMia.' },
    'wedding-guest-outfit-ideas': { title: 'Wedding Guest Outfit Ideas | LuxeMia Blog', description: 'Wedding guest outfit ideas for Indian weddings at LuxeMia.' },
    'saree-draping-styles-every-occasion': { title: 'Saree Draping Styles for Every Occasion | LuxeMia Blog', description: 'Different saree draping styles at LuxeMia.' },
    'indian-wedding-trends-2026': { title: 'Indian Wedding Trends 2026 | LuxeMia Blog', description: 'Top Indian wedding trends for 2026 at LuxeMia.' },
    'lehenga-color-for-dark-skin': { title: 'Best Lehenga Colors for Dark Skin Tones | LuxeMia Blog', description: 'Perfect lehenga color for dark skin tones at LuxeMia.' },
    'wedding-saree-for-mother-of-bride': { title: 'Wedding Saree for Mother of the Bride | LuxeMia Blog', description: 'Wedding saree options for the mother of the bride at LuxeMia.' },
    'designer-wedding-dress-under-500': { title: 'Designer Wedding Dress Under $500 | LuxeMia Blog', description: 'Designer wedding dresses under $500 at LuxeMia.' },
    'nri-wedding-ethnic-wear-trends-2026': { title: 'NRI Wedding Ethnic Wear Trends 2026 | LuxeMia Blog', description: 'NRI wedding ethnic wear trends for 2026 at LuxeMia.' },
    'buy-authentic-indian-sarees-online-usa-uk': { title: 'How to Buy Authentic Indian Sarees Online | LuxeMia Blog', description: 'Guide to buying authentic Indian sarees online at LuxeMia.' },
    'styling-indian-ethnic-wear-festive-occasions-abroad': { title: 'Styling Indian Ethnic Wear Abroad | LuxeMia Blog', description: 'Styling Indian ethnic wear for festive occasions abroad at LuxeMia.' },
    'accessorize-indian-ethnic-wear': { title: 'How to Accessorize Indian Ethnic Wear Like a Pro | LuxeMia Blog', description: 'Complete your ethnic ensemble with the perfect accessories. From traditional jewelry to contemporary additions.' },
    'caring-for-silk-sarees': { title: 'Expert Tips for Caring for Your Precious Silk Sarees | LuxeMia Blog', description: 'Learn professional techniques to maintain, store, and preserve your silk sarees for generations.' },
    'how-to-measure-yourself-for-indian-ethnic-wear': { title: 'How to Measure Yourself for Indian Ethnic Wear | LuxeMia Blog', description: 'Step-by-step home measuring guide for lehenga, saree blouse, and salwar kameez by professional tailors.' },
    'what-to-wear-indian-wedding-guest-2026': { title: 'What to Wear to an Indian Wedding as a Guest 2026 | LuxeMia Blog', description: 'Complete guest outfit guide for Indian weddings — mehendi to reception, by dress code and budget.' },
    'lehenga-vs-anarkali-which-is-right-for-you': { title: 'Lehenga vs Anarkali: Which Style Suits You Best? | LuxeMia Blog', description: 'Key differences between lehenga choli and anarkali suits for different occasions and body types.' },
    'nri-guide-buying-indian-ethnic-wear-online-usa-uk-canada': { title: 'NRI Guide: Buy Indian Ethnic Wear Online from USA, UK & Canada | LuxeMia Blog', description: 'Practical guide for NRI shoppers — sizing, duty-free limits, and quality checks for buying Indian ethnic wear online.' },
    'care-guide-washing-storing-indian-ethnic-wear': { title: 'How to Care for Indian Ethnic Wear: Washing & Storing | LuxeMia Blog', description: 'Special care guide for lehengas, sarees, and salwar kameez with zardozi, mirror work, and silk embroidery.' },
    'buying-indian-ethnic-wear-online-usa': { title: 'Complete Guide to Buying Indian Ethnic Wear Online from USA | LuxeMia Blog', description: 'Definitive guide for NRIs buying Indian clothes from the USA — sizing, shipping, customs, and authenticity.' },
    'banarasi-silk-saree-guide-authentic': { title: 'Banarasi Silk Sarees: History & How to Spot a Fake | LuxeMia Blog', description: 'Deep dive into Varanasi weaving traditions, types of Banarasi silk, and tips to identify authentic handloom.' },
    'how-to-drape-saree-beginner-guide': { title: 'How to Drape a Saree: Step-by-Step Guide for Beginners | LuxeMia Blog', description: 'Master the classic Nivi saree draping style with our beginner-friendly guide including pallu styling tips.' },
    'indian-wedding-ceremony-outfit-guide': { title: 'Indian Wedding Ceremony Outfit Guide: Mehendi to Reception | LuxeMia Blog', description: 'Per-ceremony outfit guide for Indian weddings — Mehendi, Haldi, Sangeet, Wedding, and Reception.' },
    'indian-fabric-types-guide-silk-georgette-chiffon': { title: 'Complete Guide to Indian Fabric Types: Silk, Georgette & More | LuxeMia Blog', description: 'Everything about Indian ethnic wear fabrics — Banarasi, Kanchipuram, georgette, chiffon, velvet, and care tips.' },
    'anarkali-suit-styling-guide-2026': { title: 'Anarkali Suit Styling Guide 2026: Casual to Bridal | LuxeMia Blog', description: 'Master styling anarkali suits — floor-length, knee-length, jacket style, with body type guide and dupatta draping.' },
    'how-to-measure-yourself-indian-ethnic-wear': { title: 'How to Measure Yourself for Indian Ethnic Wear: Sizing Guide | LuxeMia Blog', description: 'Detailed guide to measuring for Indian ethnic wear — bust, waist, hips, shoulder, with international size conversion.' },
    'kanchipuram-silk-saree-south-indian-wedding-guide': { title: 'Kanchipuram Silk Sarees: South Indian Wedding Guide | LuxeMia Blog', description: 'Complete guide to Kanchipuram (Kanjivaram) silk sarees — history, authentication, pricing, and bridal styling.' },
    'zari-work-guide-indian-embroidery-gold-silver-thread': { title: 'The Art of Zari Work: Golden Thread Tradition | LuxeMia Blog', description: 'Discover the centuries-old art of zari embroidery — authentic zari identification, styles, and garment care tips.' },
    'chikankari-embroidery-lucknow-guide': { title: 'Chikankari Embroidery of Lucknow: Shadow Work Guide | LuxeMia Blog', description: 'Explore Lucknowi chikankari — Mughal origins, stitch types, identifying authentic pieces, and shopping online.' },
  };
  return blogMap[slug] || null;
}

export const config = {
  matcher: [
    '/((?!_prerender|assets|api|favicon\\.ico|og-image\\.jpg|robots\\.txt|sitemap\\.xml|images|catalogs|3c4a52b9-542f-4bfe-a61b-9afb42f4312c\\.txt|google4e3f332d00afc8ba\\.html|.*\\.(?:js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2|csv|txt|xml|tsv)).*)',
  ],
};
