import { rewrite, next } from '@vercel/functions';

/**
 * Vercel Edge Middleware (non-Next.js / Vite)
 *
 * Detects search engine bot user agents and either serves pre-rendered HTML
 * or dynamically generates product page HTML with proper SEO content.
 * Regular users get the normal SPA experience.
 *
 * KEY FIX: Product pages are NO LONGER rewritten to non-existent prerendered
 * HTML files. Instead, the middleware fetches product data from the Shopify
 * Storefront API and generates proper HTML with meta tags, structured data,
 * and visible content for Googlebot / GMC crawlers.
 */

const BOT_USER_AGENTS = [
  'googlebot',
  'google-inspectiontool',
  'google-InspectionTool',
  'bingbot',
  'yandexbot',
  'duckduckbot',
  'baiduspider',
  'slurp',
  'sogou',
  'facebookexternalhit',
  'facebot',
  'twitterbot',
  'linkedinbot',
  'whatsapp',
  'telegrambot',
  'applebot',
  'pinterestbot',
  'redditbot',
  'oai-searchbot',
  'perplexitybot',
  'claudebot',
  'gptbot',
  'ia_archiver',
  'semrushbot',
  'ahrefsbot',
  'mj12bot',
  'dotbot',
  'petalbot',
  'bytespider',
];

// Routes that have static prerendered HTML files (generated by prerender.js)
const PRERENDERED_ROUTES = new Set([
  '/',
  '/suits',
  '/lehengas',
  '/sarees',
  '/menswear',
  '/blog',
  '/blog/sharara-suit-guide-2026-styles-fabrics',
  '/blog/pakistani-suits-anarkali-shopping-guide',
  '/blog/style-lehenga-choli-every-wedding-event',
  '/blog/indian-wedding-season-2026-outfit-guide',
  '/blog/fabric-guide-indian-ethnic-wear-georgette-silk-chiffon',
  '/blog/indian-wedding-dress-complete-guide',
  '/blog/red-bridal-lehenga-trends-2026',
  '/blog/designer-wedding-dress-under-50000',
  '/blog/wedding-guest-outfit-ideas',
  '/blog/saree-draping-styles-every-occasion',
  '/blog/indian-wedding-trends-2026',
  '/blog/lehenga-color-for-dark-skin',
  '/blog/wedding-saree-for-mother-of-bride',
  '/blog/designer-wedding-dress-under-500',
  '/blog/nri-wedding-ethnic-wear-trends-2026',
  '/blog/buy-authentic-indian-sarees-online-usa-uk',
  '/blog/styling-indian-ethnic-wear-festive-occasions-abroad',
  '/collections',
  '/brand-story',
  '/new-arrivals',
  '/bestsellers',
  '/indowestern',
  '/nri',
  '/nri/usa',
  '/nri/uk',
  '/nri/canada',
  '/indian-ethnic-wear-usa',
  '/indian-ethnic-wear-uk',
  '/indian-ethnic-wear-canada',
  '/style-consultation',
  '/style-quiz',
  '/size-guide',
  '/care-guide',
  '/faq',
  '/shipping',
  '/returns',
  '/contact',
  '/artisans',
  '/sustainability',
  '/virtual-try-on',
  '/products',
  '/privacy',
  '/terms',
  '/press',
  // NOTE: Product pages (/product/*) are NOT listed here because prerender.js
  // does NOT generate static HTML for them. Instead, the middleware dynamically
  // generates HTML for product pages when visited by bots.
]);

// Routes that redirect elsewhere (should not be treated as 404)
const REDIRECT_ROUTES = new Set([
  '/our-story',
  '/lookbook',
  '/jewelry',
  '/collections/wedding-sarees',
  '/collections/bridal-lehengas',
  '/collections/reception-outfits',
  '/collections/festive-wear',
  '/collections/sarees',
  '/collections/salwar-kameez',
  '/collections/suits',
  '/collections/menswear',
  '/collections/lehengas',
  '/collections/indo-western',
  '/collections/bridesmaid-dresses',
  '/collections/groomsman-outfits',
]);

// Shopify Storefront API config for dynamic product page rendering
const SHOPIFY_STORE_DOMAIN = 'lovable-project-zlh0w.myshopify.com';
const SHOPIFY_API_VERSION = '2025-07';
const SHOPIFY_STOREFRONT_URL = `https://${SHOPIFY_STORE_DOMAIN}/api/${SHOPIFY_API_VERSION}/graphql.json`;
const SHOPIFY_STOREFRONT_TOKEN = 'c98d10d5abd95e6a8d6ddbed223ef4b4';

const PRODUCT_BY_HANDLE_QUERY = `
  query GetProductByHandle($handle: String!) {
    productByHandle(handle: $handle) {
      id
      title
      description
      handle
      vendor
      productType
      availableForSale
      priceRange {
        minVariantPrice {
          amount
          currencyCode
        }
      }
      compareAtPriceRange {
        minVariantPrice {
          amount
          currencyCode
        }
      }
      images(first: 5) {
        edges {
          node {
            url
            altText
          }
        }
      }
      options {
        name
        values
      }
    }
  }
`;

function isBot(userAgent: string): boolean {
  const ua = userAgent.toLowerCase();
  return BOT_USER_AGENTS.some((bot) => ua.includes(bot));
}

// In-memory cache for product data (Edge Function instance reuse)
const productCache = new Map<string, { data: any; timestamp: number }>();
const CACHE_TTL = 10 * 60 * 1000; // 10 minutes

/**
 * Fetch product data from Shopify Storefront API
 */
async function fetchProduct(handle: string): Promise<any> {
  // Check cache first
  const cached = productCache.get(handle);
  if (cached && Date.now() - cached.timestamp < CACHE_TTL) {
    return cached.data;
  }

  try {
    const response = await fetch(SHOPIFY_STOREFRONT_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Shopify-Storefront-Access-Token': SHOPIFY_STOREFRONT_TOKEN,
      },
      body: JSON.stringify({
        query: PRODUCT_BY_HANDLE_QUERY,
        variables: { handle },
      }),
    });

    if (!response.ok) return null;

    const data = await response.json();
    if (data.errors || !data.data?.productByHandle) return null;

    const product = data.data.productByHandle;

    // Cache the result
    productCache.set(handle, { data: product, timestamp: Date.now() });

    return product;
  } catch (error) {
    console.error('Error fetching product for bot:', error);
    return null;
  }
}

/**
 * Ensure image URL is forced to JPEG format (not WebP) for GMC compliance
 */
function ensureJpegUrl(url: string): string {
  if (!url) return url;
  // For Shopify CDN images, ensure format=jpg is present
  if (url.includes('cdn.shopify.com') || url.includes('myshopify.com')) {
    // Remove any existing format parameter
    let cleanUrl = url.replace(/[&?]format=\w+/g, '');
    // Remove any existing crop parameter
    cleanUrl = cleanUrl.replace(/[&?]crop=[^&]+/g, '');
    const separator = cleanUrl.includes('?') ? '&' : '?';
    return `${cleanUrl}${separator}width=1200&crop=center&format=jpg`;
  }
  return url;
}

/**
 * Generate full HTML page for a product when visited by a bot.
 * This is the CRITICAL fix for "Product page unavailable" GMC error.
 */
function generateProductHtml(product: any, handle: string): string {
  const siteUrl = 'https://luxemia.shop';
  const productUrl = `${siteUrl}/product/${handle}`;
  const title = product.title || 'Product | LuxeMia';
  const description = (product.description || '').slice(0, 300);
  const imageUrl = ensureJpegUrl(product.images?.edges?.[0]?.node?.url || `${siteUrl}/og-image.jpg`);
  const price = product.priceRange?.minVariantPrice?.amount || '0';
  const currency = product.priceRange?.minVariantPrice?.currencyCode || 'USD';
  const compareAtPrice = product.compareAtPriceRange?.minVariantPrice?.amount;
  const availability = product.availableForSale !== false ? 'InStock' : 'OutOfStock';
  const productType = product.productType || 'Ethnic Wear';
  const vendor = product.vendor || 'LuxeMia';

  // Get color and material from options
  const colorOption = product.options?.find((o: any) => o.name?.toLowerCase() === 'color');
  const materialOption = product.options?.find((o: any) =>
    o.name?.toLowerCase() === 'fabric' || o.name?.toLowerCase() === 'material'
  );
  const color = colorOption?.values?.[0] || '';
  const material = materialOption?.values?.[0] || '';

  // All product images (forced to JPEG)
  const allImages = (product.images?.edges || []).map((e: any) => ensureJpegUrl(e.node.url));

  // Price display
  const priceNum = parseFloat(price);
  const displayPrice = currency === 'USD' ? `$${price}` : `${currency} ${price}`;
  const displayCompare = compareAtPrice ? (currency === 'USD' ? `$${compareAtPrice}` : `${currency} ${compareAtPrice}`) : '';

  // Product schema for rich snippets
  const productSchema = {
    '@context': 'https://schema.org',
    '@type': 'Product',
    name: title,
    image: allImages,
    description: description,
    sku: product.id,
    url: productUrl,
    brand: { '@type': 'Brand', name: vendor },
    category: productType,
    ...(color && { color }),
    ...(material && { material }),
    itemCondition: 'https://schema.org/NewCondition',
    offers: {
      '@type': 'Offer',
      url: productUrl,
      price: price,
      priceCurrency: currency,
      priceValidUntil: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      availability: `https://schema.org/${availability}`,
      itemCondition: 'https://schema.org/NewCondition',
      seller: { '@type': 'Organization', name: 'LuxeMia' },
      shippingDetails: {
        '@type': 'OfferShippingDetails',
        shippingRate: { '@type': 'MonetaryAmount', value: '14.95', currency: currency },
        freeShippingThreshold: { '@type': 'MonetaryAmount', value: '300', currency: currency },
        shippingDestination: { '@type': 'DefinedRegion', addressCountry: ['US', 'GB', 'AE', 'CA', 'AU'] },
        deliveryTime: {
          '@type': 'ShippingDeliveryTime',
          handlingTime: {
            '@type': 'QuantitativeValue',
            minValue: 3, maxValue: 7, unitCode: 'DAY',
            description: '3-5 business days for readymade; 5-7 business days for custom/alterations',
          },
          transitTime: {
            '@type': 'QuantitativeValue',
            minValue: 3, maxValue: 10, unitCode: 'DAY',
            description: '3-5 business days via DHL Express; 7-10 business days via USPS/UPS Standard',
          },
        },
      },
      hasMerchantReturnPolicy: {
        '@type': 'MerchantReturnPolicy',
        applicableCountry: ['US', 'GB', 'CA', 'AU', 'AE'],
        returnPolicyCategory: 'https://schema.org/MerchantReturnNotPermitted',
        merchantReturnDays: 0,
        description: 'All sales are final. Returns are not accepted. Only genuine shipping damage claims are handled within 7 days of delivery with photo/video evidence.',
      },
    },
  };

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)} | ${escapeHtml(productType)} | LuxeMia</title>
  <meta name="description" content="${escapeHtml(description)}">
  <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">
  <meta name="googlebot" content="index, follow, max-image-preview:large">
  <link rel="canonical" href="${productUrl}">

  <!-- Open Graph -->
  <meta property="og:type" content="product">
  <meta property="og:url" content="${productUrl}">
  <meta property="og:title" content="${escapeHtml(title)} | LuxeMia">
  <meta property="og:description" content="${escapeHtml(description)}">
  <meta property="og:image" content="${imageUrl}">
  <meta property="og:site_name" content="LuxeMia">
  <meta property="og:locale" content="en_US">
  <meta property="product:price:amount" content="${price}">
  <meta property="product:price:currency" content="${currency}">
  <meta property="product:availability" content="${availability === 'InStock' ? 'in stock' : 'out of stock'}">
  <meta property="product:brand" content="${escapeHtml(vendor)}">
  <meta property="product:condition" content="new">

  <!-- Twitter Card -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:url" content="${productUrl}">
  <meta name="twitter:title" content="${escapeHtml(title)} | LuxeMia">
  <meta name="twitter:description" content="${escapeHtml(description)}">
  <meta name="twitter:image" content="${imageUrl}">

  <!-- Structured Data -->
  <script type="application/ld+json">${JSON.stringify(productSchema)}</script>

  <!-- Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700&family=Lora:wght@400;500;600;700&display=swap" rel="stylesheet">

  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Lora', Georgia, serif; color: #1a1a1a; background: #fafaf9; line-height: 1.6; }
    .container { max-width: 1200px; margin: 0 auto; padding: 0 16px; }
    .breadcrumb { font-size: 14px; color: #78716c; padding: 24px 0; }
    .breadcrumb a { color: #78716c; text-decoration: none; }
    .breadcrumb a:hover { color: #1a1a1a; }
    .product-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 48px; padding: 0 0 64px; }
    .product-images img { width: 100%; height: auto; border-radius: 2px; }
    .product-info h1 { font-family: 'Playfair Display', Georgia, serif; font-size: 28px; font-weight: 600; margin-bottom: 12px; }
    .price { font-size: 24px; font-weight: 600; margin-bottom: 16px; }
    .price .compare { text-decoration: line-through; color: #78716c; font-size: 18px; margin-left: 8px; }
    .description { color: #57534e; font-size: 15px; margin-bottom: 24px; }
    .details { font-size: 14px; color: #57534e; }
    .details dt { font-weight: 600; color: #1a1a1a; margin-top: 8px; }
    .shipping-info { background: #f5f5f4; border-radius: 8px; padding: 16px; margin-top: 24px; font-size: 13px; color: #57534e; }
    .shipping-info strong { color: #1a1a1a; }
    .cta { display: inline-block; background: #1a1a1a; color: #fff; padding: 12px 32px; border-radius: 2px; text-decoration: none; font-size: 14px; margin-top: 24px; }
    @media (max-width: 768px) { .product-grid { grid-template-columns: 1fr; gap: 24px; } }
  </style>
</head>
<body>
  <div class="container">
    <nav class="breadcrumb">
      <a href="${siteUrl}">Home</a> &rsaquo;
      <a href="${siteUrl}/${productType.toLowerCase().includes('saree') ? 'sarees' : productType.toLowerCase().includes('lehenga') ? 'lehengas' : productType.toLowerCase().includes('sherwani') || productType.toLowerCase().includes('kurta') || productType.toLowerCase().includes('menswear') ? 'menswear' : 'suits'}">${escapeHtml(productType)}</a> &rsaquo;
      <span>${escapeHtml(title)}</span>
    </nav>

    <div class="product-grid">
      <div class="product-images">
        <img src="${imageUrl}" alt="${escapeHtml(title)}" loading="eager" width="600" height="800">
        ${allImages.length > 1 ? allImages.slice(1).map((img: string, i: number) =>
          `<img src="${img}" alt="${escapeHtml(title)} - Image ${i + 2}" loading="lazy" width="600" height="800" style="margin-top:8px">`
        ).join('') : ''}
      </div>

      <div class="product-info">
        <h1>${escapeHtml(title)}</h1>
        <div class="price">
          ${displayPrice}
          ${displayCompare && parseFloat(compareAtPrice) > priceNum ? `<span class="compare">${displayCompare}</span>` : ''}
        </div>
        <p class="description">${escapeHtml(description)}</p>

        <dl class="details">
          <dt>Brand</dt><dd>${escapeHtml(vendor)}</dd>
          <dt>Category</dt><dd>${escapeHtml(productType)}</dd>
          ${color ? `<dt>Color</dt><dd>${escapeHtml(color)}</dd>` : ''}
          ${material ? `<dt>Fabric</dt><dd>${escapeHtml(material)}</dd>` : ''}
          <dt>Condition</dt><dd>New</dd>
          <dt>Availability</dt><dd>${availability === 'InStock' ? 'In Stock' : 'Out of Stock'}</dd>
        </dl>

        <div class="shipping-info">
          <strong>Shipping:</strong> Flat rate $14.95 per item worldwide. Free on orders over $300.<br>
          <strong>Dispatch:</strong> Ready-made 3-5 business days | Custom/alterations 5-7 business days.<br>
          <strong>Delivery:</strong> 3-5 business days via DHL Express | 7-10 business days via USPS/UPS Standard.<br>
          <strong>Returns:</strong> All sales final. Shipping damage claims within 7 days with photo/video evidence.
        </div>

        <a href="${productUrl}" class="cta">View Full Details &amp; Buy</a>
      </div>
    </div>
  </div>
</body>
</html>`;
}

function escapeHtml(text: string): string {
  return (text || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// Cached 404 HTML - will be populated on first request
let cached404Html: string | null = null;

/**
 * Return a proper HTTP 404 response with the 404 page content.
 */
async function return404(request: Request): Promise<Response> {
  if (!cached404Html) {
    try {
      const resp = await fetch(new URL('/_prerender/404.html', request.url).toString());
      cached404Html = await resp.text();
    } catch {
      cached404Html = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page Not Found | LuxeMia</title><meta name="robots" content="noindex,nofollow"></head><body><h1>Page Not Found</h1><p>The page you are looking for could not be found.</p></body></html>`;
    }
  }
  return new Response(cached404Html, {
    status: 404,
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'public, max-age=300',
    },
  });
}

export default async function middleware(request: Request) {
  const userAgent = request.headers.get('user-agent') || '';
  const url = new URL(request.url);
  const { pathname } = url;

  // Skip non-page requests (static files, API, etc.)
  if (
    pathname.startsWith('/_prerender') ||
    pathname.startsWith('/assets') ||
    pathname.startsWith('/api') ||
    pathname.startsWith('/catalogs') ||
    pathname.includes('.')
  ) {
    return next();
  }

  // For bots: serve prerendered or dynamically generated HTML
  if (isBot(userAgent)) {
    // ─── PRODUCT PAGES ─────────────────────────────────────
    // CRITICAL FIX: Generate HTML dynamically for ALL product pages.
    // Previously, product pages in PRERENDERED_ROUTES were rewritten to
    // non-existent prerendered HTML files, causing 404s for Googlebot.
    // Now we fetch product data from Shopify and generate proper HTML.
    if (pathname.startsWith('/product/')) {
      const handle = pathname.replace('/product/', '');
      const product = await fetchProduct(handle);

      if (product) {
        const html = generateProductHtml(product, handle);
        return new Response(html, {
          status: 200,
          headers: {
            'Content-Type': 'text/html; charset=utf-8',
            'Cache-Control': 'public, s-maxage=600, stale-while-revalidate=3600',
            'X-Robots-Tag': 'index, follow',
          },
        });
      }

      // Product not found in Shopify — return 404 with noindex
      return new Response(
        `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Product Not Found | LuxeMia</title><meta name="robots" content="noindex,nofollow"></head><body><h1>Product Not Found</h1><p>This product could not be found. <a href="https://luxemia.shop">Return to homepage</a></p></body></html>`,
        {
          status: 404,
          headers: {
            'Content-Type': 'text/html; charset=utf-8',
            'Cache-Control': 'public, max-age=300',
          },
        }
      );
    }

    // ─── STATIC PRERENDERED PAGES ──────────────────────────
    if (PRERENDERED_ROUTES.has(pathname)) {
      const prerenderPath =
        pathname === '/'
          ? '/_prerender/index.html'
          : `/_prerender${pathname}.html`;

      return rewrite(new URL(prerenderPath, request.url));
    }

    // Collection/category pages that aren't prerendered — let through to SPA
    if (pathname.startsWith('/collections/')) {
      return next();
    }

    // /admin should return noindex to bots
    if (pathname.startsWith('/admin')) {
      return new Response(
        `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Admin | LuxeMia</title></head><body><p>Admin panel — not indexed.</p></body></html>`,
        {
          status: 200,
          headers: { 'Content-Type': 'text/html; charset=utf-8' },
        }
      );
    }

    // Unknown route that's not a redirect → return proper HTTP 404
    if (!REDIRECT_ROUTES.has(pathname)) {
      return return404(request);
    }
  }

  // Regular users or redirect routes → normal SPA experience
  return next();
}

export const config = {
  matcher: [
    '/((?!_prerender|assets|favicon\\.ico|og-image\\.jpg|robots\\.txt|sitemap\\.xml|images|catalogs|3c4a52b9-542f-4bfe-a61b-9afb42f4312c\\.txt|google4e3f332d00afc8ba\\.html|merchant-feed\\.xml|merchant-feed\\.tsv|.*\\.(?:js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2|csv|txt|xml|tsv)).*)',
  ],
};
